version: '3.8'

services:
  backend:
    build:
      context: .  # Refers to the current directory where docker-compose.yml and Dockerfile are located
    ports:
      - "8000:8000"
    environment:
      - ENV=production

  frontend:
    build:
      context: app/ui-app
    ports:
      - "80:80"
    depends_on:
      - backend